# Generated by Django 4.2.10 on 2024-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='stause',
        ),
    ]
