# Generated by Django 4.2.10 on 2024-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_device_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='Net_mask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Net_mask'),
        ),
    ]
