# Generated by Django 4.2.10 on 2024-02-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_devices_net_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='Net_mask',
        ),
    ]
