# Generated by Django 4.2.10 on 2024-02-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_devices_net_mask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='Mack',
            new_name='serial',
        ),
    ]
