# Generated by Django 4.2.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_rename_mack_devices_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='serial',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='serial number'),
        ),
    ]
