# Generated by Django 4.2.10 on 2024-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_devices_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('su_net', models.GenericIPAddressField(verbose_name='IP Address')),
                ('gate_way', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
        ),
    ]
