# Generated by Django 4.2.10 on 2024-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_ip_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_edit',
            name='gate_way',
            field=models.GenericIPAddressField(verbose_name='Gateway ip'),
        ),
        migrations.AlterField(
            model_name='ip_edit',
            name='su_net',
            field=models.GenericIPAddressField(verbose_name='subnet mask'),
        ),
    ]
