# Generated by Django 4.2.10 on 2024-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_ip_edit_gate_way_alter_ip_edit_su_net'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ip_edit',
        ),
        migrations.AddField(
            model_name='devices',
            name='gate_way',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Gateway ip'),
        ),
        migrations.AddField(
            model_name='devices',
            name='new_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='devices',
            name='su_net',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='subnet mask'),
        ),
    ]
