# Generated by Django 4.2.10 on 2024-03-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_delete_ip_edit_devices_gate_way_devices_new_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='packeges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packege_name', models.CharField(blank=True, max_length=90, null=True)),
                ('packege_cost', models.IntegerField(blank=True, null=True, verbose_name='Packege Cost')),
                ('packege_hours', models.IntegerField(blank=True, null=True, verbose_name='Number of Hours')),
            ],
        ),
        migrations.RemoveField(
            model_name='devices',
            name='new_ip',
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriberid', models.IntegerField(verbose_name='Subscriber Id')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Name')),
                ('card', models.IntegerField(verbose_name='Card Number')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Valid TO')),
                ('packege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.packeges', verbose_name='Packege')),
            ],
        ),
    ]
