# Generated by Django 4.2.10 on 2024-03-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_packeges_remove_devices_new_ip_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriberid',
        ),
    ]
