# Generated by Django 4.2.10 on 2024-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_subscriber_subscriberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriberid',
            field=models.IntegerField(default=1, verbose_name='Subscriber Id'),
            preserve_default=False,
        ),
    ]
