# Generated by Django 4.2.10 on 2024-03-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_counting'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=80, null=True, verbose_name='User')),
                ('userid', models.IntegerField(blank=True, null=True, verbose_name='Ticket id')),
                ('entrytime', models.DateTimeField(blank=True, null=True, verbose_name='Entry Time')),
                ('exitetime', models.DateTimeField(blank=True, null=True, verbose_name='Exite Time')),
                ('totaltime', models.DateTimeField(blank=True, null=True, verbose_name='Total Time')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Cost')),
                ('entrypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.devices', verbose_name='Entry Point')),
            ],
        ),
    ]
