# Generated by Django 4.2.10 on 2024-04-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_counting_user_delete_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='counting',
        ),
    ]
