# Generated by Django 4.2.10 on 2024-04-01 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0017_delete_counting'),
    ]

    operations = [
        migrations.CreateModel(
            name='counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Code')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Entry Time')),
                ('exite_time', models.DateTimeField(blank=True, null=True, verbose_name='Exite Time')),
                ('total_time', models.DateTimeField(blank=True, null=True, verbose_name='Total Time')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Cost')),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.devices', verbose_name='Entry Point')),
            ],
        ),
    ]
