# Generated by Django 4.2.10 on 2024-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_rename_counting_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='entry_point',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Entry Point'),
        ),
    ]
