# Generated by Django 4.2.10 on 2024-04-19 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0020_alter_transactions_entry_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='exite_time',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='total_time',
        ),
        migrations.CreateModel(
            name='counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exite_time', models.DateTimeField(blank=True, null=True, verbose_name='Exite Time')),
                ('total_time', models.DateTimeField(blank=True, null=True, verbose_name='Total Time')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Cost')),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
