# Generated by Django 4.2.10 on 2024-04-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_remove_transactions_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counting',
            name='total_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Time'),
        ),
    ]
