# Generated by Django 4.2.10 on 2024-04-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_alter_counting_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='User',
        ),
    ]
