# Generated by Django 4.2.10 on 2024-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0023_remove_transactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='counting',
            name='entry_point',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Entry Point'),
        ),
        migrations.AddField(
            model_name='counting',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry Time'),
        ),
    ]
