# Generated by Django 4.2.10 on 2024-06-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0026_subscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='creatrd_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Createdat'),
        ),
    ]
