# Generated by Django 4.2.10 on 2024-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0028_transactions_creatrd_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='creatrd_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Createdat'),
        ),
    ]
