# Generated by Django 4.2.10 on 2024-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0029_counting_creatrd_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='counting_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_period_duration', models.FloatField(blank=True, null=True, verbose_name='first period duration')),
                ('second_period_duration', models.FloatField(blank=True, null=True, verbose_name='second period duration')),
                ('rest_period_duration', models.FloatField(blank=True, null=True, verbose_name='rest period duration')),
                ('first_period_duration_cost', models.FloatField(blank=True, null=True, verbose_name='first period duration cost')),
                ('second_period_duration_cost', models.FloatField(blank=True, null=True, verbose_name='second period duration cost')),
                ('rest_period_duration_cost', models.FloatField(blank=True, null=True, verbose_name='rest period duration cost')),
            ],
        ),
    ]
