# Generated by Django 4.2.10 on 2024-06-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0030_counting_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting_settings',
            name='enable_night_mode',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable night mode'),
        ),
        migrations.AddField(
            model_name='counting_settings',
            name='n_endtime',
            field=models.TimeField(blank=True, null=True, verbose_name='night mode end time'),
        ),
        migrations.AddField(
            model_name='counting_settings',
            name='n_starttime',
            field=models.TimeField(blank=True, null=True, verbose_name='night mode start time'),
        ),
        migrations.AddField(
            model_name='counting_settings',
            name='night_modeCost',
            field=models.FloatField(blank=True, null=True, verbose_name='night mode cost'),
        ),
    ]
