# Generated by Django 4.2.10 on 2024-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0031_counting_settings_enable_night_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counting_settings',
            name='rest_period_duration',
            field=models.FloatField(default=False, verbose_name='rest period duration'),
        ),
    ]
