# Generated by Django 4.2.10 on 2024-07-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0032_alter_counting_settings_rest_period_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting_settings',
            name='period_of_allowing',
            field=models.FloatField(default=10, verbose_name='period of allowing'),
        ),
    ]
