# Generated by Django 4.2.10 on 2024-07-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0033_counting_settings_period_of_allowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counting_settings',
            name='rest_period_duration',
        ),
    ]
