# Generated by Django 4.2.10 on 2024-07-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0034_remove_counting_settings_rest_period_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counting_settings',
            old_name='rest_period_duration_cost',
            new_name='rest_period_duration_cost_perhoure',
        ),
    ]
