# Generated by Django 4.2.10 on 2024-07-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0035_rename_rest_period_duration_cost_counting_settings_rest_period_duration_cost_perhoure'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting_settings',
            name='min_period_tocost',
            field=models.FloatField(blank=True, null=True, verbose_name='minimum period to cost night mode'),
        ),
    ]
